#
# version: 2.1
# orbs:
#   cypress: cypress-io/cypress@1.0.0
# workflows:
#   build:
#     jobs:
#       - cypress/run:
#           executor: cypress/base-8
    
version: 2.1
orbs:
  cypress: cypress-io/cypress@1
jobs:
  build:
    docker:
      - image: solisoft/fasty
    steps:
      - checkout
      - run: cp foxxy/app/js/config.js.sample foxxy/app/js/config.js
      - run:
          name: "start cms"
          command: /bin/bash -c "lapis server"
          background: true
      - cypress/run